CMS-3417 - add deterministic hss status check
Add a sync command after each section to make sure we force to disk
as often as possible in hopes to avoid shutdown/packaging weirdness.

Instead of sleeping and hoping HSS is up, query hssctl and block
until it is up.  Has a 20 minute timeout at which time it will raise an
exception since you aren't going anywhere, anyway.

FAILURE EXAMPLE
johnn@romulus:~$ ./test.py
No hosts found. Please specify (single) host string for connection: root@pluto-smw
[root@pluto-smw] Login password for 'root':
0 of 12 HSS processes running
..sleeping for 30 seconds (1/5 tries)
0 of 12 HSS processes running
..sleeping for 30 seconds (2/5 tries)
0 of 12 HSS processes running
..sleeping for 30 seconds (3/5 tries)
0 of 12 HSS processes running
..sleeping for 30 seconds (4/5 tries)
0 of 12 HSS processes running
..sleeping for 30 seconds (5/5 tries)
Traceback (most recent call last):
  File "./test.py", line 83, in <module>
    wait_for_hss(sleep_secs = 30, giveup=5)
  File "./test.py", line 78, in wait_for_hss
    raise RuntimeError("HSS has failed to start for {} minutes, giving up!".format((attempt*sleep_secs)/60))
RuntimeError: HSS has failed to start for 2 minutes, giving up!
johnn@romulus:~$

SUCCESS EXAMPLE
johnn@romulus:~$ ./test.py
No hosts found. Please specify (single) host string for connection: root@pluto-smw
[root@pluto-smw] Login password for 'root':
0 of 12 HSS processes running
..sleeping for 30 seconds (1/5 tries)
6 of 12 HSS processes running
..sleeping for 30 seconds (2/5 tries)
HSS is up!
johnn@romulus:~$